// ──────────────────────────────────────────────────────────────
// MEMORY WORK SUPPLEMENTS — Sample Data
// ──────────────────────────────────────────────────────────────
// week: null  = full-cycle bundle (shows for any week filter)
// week: N     = specific week

export const SUPPLEMENTS = [

  // ── Grammar ──────────────────────────────────────────────────
  {
    id: 1,
    title: 'Cycle 1 Grammar Flashcard Bundle',
    type: 'Flashcards',
    subject: 'Grammar',
    cycle: 1,
    week: null,
    price: 'paid',
    source: 'Teachers Pay Teachers',
    url: 'https://www.teacherspayteachers.com/Browse/Search:classical+conversations+cycle+1+grammar+flashcards',
  },
  {
    id: 2,
    title: 'Cycle 2 Grammar Flashcard Bundle',
    type: 'Flashcards',
    subject: 'Grammar',
    cycle: 2,
    week: null,
    price: 'paid',
    source: 'Teachers Pay Teachers',
    url: 'https://www.teacherspayteachers.com/Browse/Search:classical+conversations+cycle+2+grammar+flashcards',
  },
  {
    id: 3,
    title: 'Cycle 3 Grammar Flashcard Bundle',
    type: 'Flashcards',
    subject: 'Grammar',
    cycle: 3,
    week: null,
    price: 'paid',
    source: 'Teachers Pay Teachers',
    url: 'https://www.teacherspayteachers.com/Browse/Search:classical+conversations+cycle+3+grammar+flashcards',
  },
  {
    id: 4,
    title: 'CC Grammar Practice Worksheets — Cycle 1',
    type: 'Worksheets',
    subject: 'Grammar',
    cycle: 1,
    week: null,
    price: 'paid',
    source: 'Teachers Pay Teachers',
    url: 'https://www.teacherspayteachers.com/Browse/Search:classical+conversations+cycle+1+grammar+worksheets',
  },
  {
    id: 5,
    title: 'Grammar Sentences Boom Deck — Cycle 2',
    type: 'Digital Games',
    subject: 'Grammar',
    cycle: 2,
    week: null,
    price: 'paid',
    source: 'Boom Learning',
    url: 'https://wow.boomlearning.com/search?q=classical+conversations+cycle+2+grammar',
  },

  // ── History ──────────────────────────────────────────────────
  {
    id: 6,
    title: 'Cycle 1 History Sentences Flashcards',
    type: 'Flashcards',
    subject: 'History',
    cycle: 1,
    week: null,
    price: 'free',
    source: 'Free Download',
    url: 'https://www.teacherspayteachers.com/Browse/Search:classical+conversations+cycle+1+history+flashcards+free',
  },
  {
    id: 7,
    title: 'Cycle 2 History Sentence Worksheets',
    type: 'Worksheets',
    subject: 'History',
    cycle: 2,
    week: null,
    price: 'paid',
    source: 'Teachers Pay Teachers',
    url: 'https://www.teacherspayteachers.com/Browse/Search:classical+conversations+cycle+2+history+worksheets',
  },
  {
    id: 8,
    title: 'Cycle 3 History Boom Cards',
    type: 'Digital Games',
    subject: 'History',
    cycle: 3,
    week: null,
    price: 'paid',
    source: 'Boom Learning',
    url: 'https://wow.boomlearning.com/search?q=classical+conversations+cycle+3+history',
  },

  // ── Timeline ─────────────────────────────────────────────────
  {
    id: 9,
    title: 'CC Timeline Cards — Printable Flashcard Set',
    type: 'Flashcards',
    subject: 'Timeline',
    cycle: 1,
    week: null,
    price: 'free',
    source: 'Free Download',
    url: 'https://www.teacherspayteachers.com/Browse/Search:classical+conversations+timeline+cards+free',
  },
  {
    id: 10,
    title: 'Timeline Sequencing Worksheets — Cycle 2',
    type: 'Worksheets',
    subject: 'Timeline',
    cycle: 2,
    week: null,
    price: 'paid',
    source: 'Teachers Pay Teachers',
    url: 'https://www.teacherspayteachers.com/Browse/Search:classical+conversations+cycle+2+timeline+worksheets',
  },
  {
    id: 11,
    title: 'Timeline Boom Cards — Cycle 3',
    type: 'Digital Games',
    subject: 'Timeline',
    cycle: 3,
    week: null,
    price: 'paid',
    source: 'Boom Learning',
    url: 'https://wow.boomlearning.com/search?q=classical+conversations+timeline',
  },

  // ── Latin ────────────────────────────────────────────────────
  {
    id: 12,
    title: 'Cycle 1 Latin Endings Flashcards',
    type: 'Flashcards',
    subject: 'Latin',
    cycle: 1,
    week: null,
    price: 'paid',
    source: 'Teachers Pay Teachers',
    url: 'https://www.teacherspayteachers.com/Browse/Search:classical+conversations+cycle+1+latin+flashcards',
  },
  {
    id: 13,
    title: 'Latin Practice Worksheets — Cycle 2',
    type: 'Worksheets',
    subject: 'Latin',
    cycle: 2,
    week: null,
    price: 'paid',
    source: 'Teachers Pay Teachers',
    url: 'https://www.teacherspayteachers.com/Browse/Search:classical+conversations+cycle+2+latin+worksheets',
  },
  {
    id: 14,
    title: 'Latin Endings Boom Deck — Cycle 1',
    type: 'Digital Games',
    subject: 'Latin',
    cycle: 1,
    week: null,
    price: 'paid',
    source: 'Boom Learning',
    url: 'https://wow.boomlearning.com/search?q=classical+conversations+latin',
  },

  // ── Math ─────────────────────────────────────────────────────
  {
    id: 15,
    title: 'CC Math Facts Skip Counting Flashcards',
    type: 'Flashcards',
    subject: 'Math',
    cycle: 1,
    week: null,
    price: 'free',
    source: 'Free Download',
    url: 'https://www.teacherspayteachers.com/Browse/Search:classical+conversations+math+facts+flashcards+free',
  },
  {
    id: 16,
    title: 'Skip Counting Practice Worksheets — All Cycles',
    type: 'Worksheets',
    subject: 'Math',
    cycle: 1,
    week: null,
    price: 'paid',
    source: 'Teachers Pay Teachers',
    url: 'https://www.teacherspayteachers.com/Browse/Search:classical+conversations+skip+counting+worksheets',
  },
  {
    id: 17,
    title: 'Math Facts Boom Cards — Cycle 2',
    type: 'Digital Games',
    subject: 'Math',
    cycle: 2,
    week: null,
    price: 'paid',
    source: 'Boom Learning',
    url: 'https://wow.boomlearning.com/search?q=classical+conversations+math+facts',
  },

  // ── Science ──────────────────────────────────────────────────
  {
    id: 18,
    title: 'Cycle 1 Science Flashcards — Classifications & Laws',
    type: 'Flashcards',
    subject: 'Science',
    cycle: 1,
    week: null,
    price: 'paid',
    source: 'Teachers Pay Teachers',
    url: 'https://www.teacherspayteachers.com/Browse/Search:classical+conversations+cycle+1+science+flashcards',
  },
  {
    id: 19,
    title: 'Cycle 2 Science Worksheets — Human Body & Biology',
    type: 'Worksheets',
    subject: 'Science',
    cycle: 2,
    week: null,
    price: 'paid',
    source: 'Teachers Pay Teachers',
    url: 'https://www.teacherspayteachers.com/Browse/Search:classical+conversations+cycle+2+science+worksheets',
  },
  {
    id: 20,
    title: 'Cycle 3 Science Boom Cards',
    type: 'Digital Games',
    subject: 'Science',
    cycle: 3,
    week: null,
    price: 'paid',
    source: 'Boom Learning',
    url: 'https://wow.boomlearning.com/search?q=classical+conversations+cycle+3+science',
  },

  // ── Geography ────────────────────────────────────────────────
  {
    id: 21,
    title: 'Cycle 1 Geography Flashcards — Europe & Americas',
    type: 'Flashcards',
    subject: 'Geography',
    cycle: 1,
    week: null,
    price: 'free',
    source: 'Free Download',
    url: 'https://www.teacherspayteachers.com/Browse/Search:classical+conversations+cycle+1+geography+flashcards+free',
  },
  {
    id: 22,
    title: 'Cycle 2 Geography Map Worksheets',
    type: 'Worksheets',
    subject: 'Geography',
    cycle: 2,
    week: null,
    price: 'paid',
    source: 'Teachers Pay Teachers',
    url: 'https://www.teacherspayteachers.com/Browse/Search:classical+conversations+cycle+2+geography+worksheets',
  },
  {
    id: 23,
    title: 'Cycle 3 Geography Boom Cards — Asia & Africa',
    type: 'Digital Games',
    subject: 'Geography',
    cycle: 3,
    week: null,
    price: 'paid',
    source: 'Boom Learning',
    url: 'https://wow.boomlearning.com/search?q=classical+conversations+cycle+3+geography',
  },

  // ── Week-specific examples ────────────────────────────────────
  {
    id: 24,
    title: 'Cycle 1 Week 1 — All Subjects Mini Pack',
    type: 'Worksheets',
    subject: 'Grammar',
    cycle: 1,
    week: 1,
    price: 'free',
    source: 'Free Download',
    url: 'https://www.teacherspayteachers.com/Browse/Search:classical+conversations+cycle+1+week+1',
  },
  {
    id: 25,
    title: 'Cycle 2 Week 12 History & Geography Pack',
    type: 'Worksheets',
    subject: 'History',
    cycle: 2,
    week: 12,
    price: 'paid',
    source: 'Teachers Pay Teachers',
    url: 'https://www.teacherspayteachers.com/Browse/Search:classical+conversations+cycle+2+week+12',
  },
  {
    id: 26,
    title: 'Cycle 3 Week 6 Science Boom Deck',
    type: 'Digital Games',
    subject: 'Science',
    cycle: 3,
    week: 6,
    price: 'paid',
    source: 'Boom Learning',
    url: 'https://wow.boomlearning.com/search?q=classical+conversations+cycle+3+week+6+science',
  },
]

export const SUBJECTS   = ['Grammar', 'History', 'Timeline', 'Latin', 'Math', 'Science', 'Geography']
export const TYPES      = ['Flashcards', 'Worksheets', 'Digital Games']
export const CYCLES     = [1, 2, 3]
