// ──────────────────────────────────────────────────────────────
// WORKSHEET DATA — Right Triangle Trig A & B
// Sourced from GeometryRightTriangleTrigPractice PDF
// ──────────────────────────────────────────────────────────────
// answerType:  "side"  → tolerance ±0.5
//              "angle" → tolerance ±1°
// triangle.pts:     { a, b, c } — [x,y] within viewBox "0 0 180 130"
// triangle.rightAt: 'a'|'b'|'c' — vertex with the right angle
// triangle.sides:   [{ v1, v2, text, dx, dy }] — label at midpoint + offset
// triangle.angles:  [{ v, text, dx, dy }] — label at vertex + offset
// ──────────────────────────────────────────────────────────────

export const WORKSHEETS = {

  trig_a: {
    id: 'trig_a',
    title: 'Right Triangle Trig A',
    description: 'Find the missing side or angle in each right triangle.',
    problems: [
      {
        id: 1,
        given:   ['Hypotenuse = 15', 'Angle = 20°'],
        find:    'the side opposite 20° — call it x',
        hint:    'sin(20°) = x / 15',
        answer:  5.13,
        answerType: 'side',
        unit: '',
        triangle: {
          pts: { a:[25,110], b:[25,20], c:[155,110] },
          rightAt: 'a',
          sides:  [{ v1:'a', v2:'b', text:'x',  dx:-16, dy:0  },
                   { v1:'b', v2:'c', text:'15', dx: 14, dy:-9 }],
          angles: [{ v:'c', text:'20°', dx:-30, dy:-14 }],
        },
      },
      {
        id: 2,
        given:   ['Adjacent side = 20', 'Angle = 35°'],
        find:    'the side opposite 35° — call it x',
        hint:    'tan(35°) = x / 20',
        answer:  14,
        answerType: 'side',
        unit: '',
        triangle: {
          pts: { a:[25,20], b:[155,20], c:[155,110] },
          rightAt: 'a',
          sides:  [{ v1:'a', v2:'b', text:'20', dx:0,   dy:-14 },
                   { v1:'b', v2:'c', text:'x',  dx: 16, dy:0   }],
          angles: [{ v:'b', text:'35°', dx:-22, dy:18 }],
        },
      },
      {
        id: 3,
        given:   ['Adjacent side = 16', 'Angle = 50°'],
        find:    'the hypotenuse — call it x',
        hint:    'cos(50°) = 16 / x',
        answer:  24.89,
        answerType: 'side',
        unit: '',
        triangle: {
          pts: { a:[25,20], b:[25,110], c:[155,20] },
          rightAt: 'a',
          sides:  [{ v1:'a', v2:'b', text:'16', dx:-16, dy:0  },
                   { v1:'b', v2:'c', text:'x',  dx: 14, dy:-9 }],
          angles: [{ v:'b', text:'50°', dx:22, dy:-14 }],
        },
      },
      {
        id: 4,
        given:   ['Hypotenuse = 18', 'Angle = 38°'],
        find:    'the side opposite 38° — call it x',
        hint:    'sin(38°) = x / 18',
        answer:  11.08,
        answerType: 'side',
        unit: '',
        triangle: {
          pts: { a:[25,110], b:[155,110], c:[155,20] },
          rightAt: 'b',
          sides:  [{ v1:'b', v2:'c', text:'x',  dx: 16, dy:0  },
                   { v1:'a', v2:'c', text:'18', dx:-14, dy:-5 }],
          angles: [{ v:'a', text:'38°', dx:26, dy:-14 }],
        },
      },
      {
        id: 5,
        given:   ['Opposite side = 16', 'Angle = 15°'],
        find:    'the side adjacent to 15° — call it x',
        hint:    'tan(15°) = 16 / x',
        answer:  59.71,
        answerType: 'side',
        unit: '',
        triangle: {
          pts: { a:[25,20], b:[25,110], c:[155,110] },
          rightAt: 'b',
          sides:  [{ v1:'a', v2:'b', text:'x',  dx:-16, dy:0  },
                   { v1:'b', v2:'c', text:'16', dx:  0, dy:16 }],
          angles: [{ v:'a', text:'15°', dx:22, dy:16 }],
        },
      },
      {
        id: 6,
        given:   ['Opposite side = 25', 'Angle = 70°'],
        find:    'the hypotenuse — call it x',
        hint:    'sin(70°) = 25 / x',
        answer:  26.6,
        answerType: 'side',
        unit: '',
        triangle: {
          pts: { a:[25,110], b:[25,20], c:[155,110] },
          rightAt: 'a',
          sides:  [{ v1:'a', v2:'b', text:'25', dx:-16, dy:0  },
                   { v1:'b', v2:'c', text:'x',  dx: 14, dy:-9 }],
          angles: [{ v:'c', text:'70°', dx:-30, dy:-14 }],
        },
      },
      {
        id: 7,
        given:   ['Leg = 9 (adjacent to θ)', 'Leg = 12 (opposite to θ)', 'Hypotenuse = 15'],
        find:    'angle θ (in degrees)',
        hint:    'cos(θ) = 9 / 15',
        answer:  53,
        answerType: 'angle',
        unit: '°',
        triangle: {
          pts: { a:[25,20], b:[25,110], c:[155,20] },
          rightAt: 'a',
          sides:  [{ v1:'a', v2:'b', text:'9',  dx:-14, dy:0   },
                   { v1:'a', v2:'c', text:'12', dx:  0, dy:-14 },
                   { v1:'b', v2:'c', text:'15', dx: 14, dy:-9  }],
          angles: [{ v:'b', text:'θ', dx:22, dy:-14 }],
        },
      },
      {
        id: 8,
        given:   ['Leg = 3 (adjacent to θ)', 'Leg = 4 (opposite to θ)'],
        find:    'angle θ (in degrees)',
        hint:    'tan(θ) = 4 / 3',
        answer:  53,
        answerType: 'angle',
        unit: '°',
        triangle: {
          pts: { a:[25,110], b:[25,20], c:[155,110] },
          rightAt: 'a',
          sides:  [{ v1:'a', v2:'b', text:'4', dx:-14, dy:0  },
                   { v1:'a', v2:'c', text:'3', dx:  0, dy:16 }],
          angles: [{ v:'c', text:'θ', dx:-22, dy:-14 }],
        },
      },
      {
        id: 9,
        given:   ['Hypotenuse = 17', 'Leg = 8 (opposite to θ)'],
        find:    'angle θ (in degrees)',
        hint:    'sin(θ) = 8 / 17',
        answer:  28,
        answerType: 'angle',
        unit: '°',
        triangle: {
          pts: { a:[25,20], b:[25,110], c:[155,110] },
          rightAt: 'b',
          sides:  [{ v1:'b', v2:'c', text:'8',  dx:  0, dy:16 },
                   { v1:'a', v2:'c', text:'17', dx: 14, dy:-6 }],
          angles: [{ v:'a', text:'θ', dx:20, dy:16 }],
        },
      },
      {
        id: 10,
        given:   ['Leg = 40 (opposite to θ)', 'Leg = 9 (adjacent to θ)'],
        find:    'angle θ (in degrees)',
        hint:    'tan(θ) = 40 / 9',
        answer:  77,
        answerType: 'angle',
        unit: '°',
        triangle: {
          pts: { a:[25,110], b:[25,20], c:[155,110] },
          rightAt: 'a',
          sides:  [{ v1:'a', v2:'b', text:'40', dx:-16, dy:0  },
                   { v1:'a', v2:'c', text:'9',  dx:  0, dy:16 }],
          angles: [{ v:'c', text:'θ', dx:-22, dy:-14 }],
        },
      },
    ],
  },

  trig_b: {
    id: 'trig_b',
    title: 'Right Triangle Trig B',
    description: 'Find the missing side or angle in each right triangle.',
    problems: [
      {
        id: 1,
        given:   ['Opposite side = 20', 'Angle = 42°'],
        find:    'the side adjacent to 42° — call it x',
        hint:    'tan(42°) = 20 / x',
        answer:  22.21,
        answerType: 'side',
        unit: '',
        triangle: {
          pts: { a:[25,110], b:[25,20], c:[155,110] },
          rightAt: 'a',
          sides:  [{ v1:'a', v2:'b', text:'20', dx:-16, dy:0  },
                   { v1:'a', v2:'c', text:'x',  dx:  0, dy:16 }],
          angles: [{ v:'c', text:'42°', dx:-30, dy:-14 }],
        },
      },
      {
        id: 2,
        given:   ['Opposite side = 18', 'Angle = 63°'],
        find:    'the hypotenuse — call it x',
        hint:    'sin(63°) = 18 / x',
        answer:  20.20,
        answerType: 'side',
        unit: '',
        triangle: {
          pts: { a:[25,20], b:[25,110], c:[155,20] },
          rightAt: 'a',
          sides:  [{ v1:'a', v2:'b', text:'18', dx:-16, dy:0  },
                   { v1:'b', v2:'c', text:'x',  dx: 14, dy:-9 }],
          angles: [{ v:'c', text:'63°', dx:-22, dy:12 }],
        },
      },
      {
        id: 3,
        given:   ['Hypotenuse = 27', 'Angle = 51°'],
        find:    'the side adjacent to 51° — call it x',
        hint:    'cos(51°) = x / 27',
        answer:  16.99,
        answerType: 'side',
        unit: '',
        triangle: {
          pts: { a:[25,20], b:[25,110], c:[155,20] },
          rightAt: 'a',
          sides:  [{ v1:'a', v2:'b', text:'x',  dx:-14, dy:0  },
                   { v1:'b', v2:'c', text:'27', dx: 14, dy:-9 }],
          angles: [{ v:'b', text:'51°', dx:22, dy:-14 }],
        },
      },
      {
        id: 4,
        given:   ['Adjacent side = 13', 'Angle = 26°'],
        find:    'the hypotenuse — call it x',
        hint:    'cos(26°) = 13 / x',
        answer:  14.46,
        answerType: 'side',
        unit: '',
        triangle: {
          pts: { a:[25,110], b:[155,110], c:[155,20] },
          rightAt: 'b',
          sides:  [{ v1:'a', v2:'b', text:'13', dx:  0, dy:16 },
                   { v1:'a', v2:'c', text:'x',  dx:-14, dy:-5 }],
          angles: [{ v:'a', text:'26°', dx:26, dy:-14 }],
        },
      },
      {
        id: 5,
        given:   ['Hypotenuse = 30', 'Angle = 35°'],
        find:    'the side adjacent to 35° — call it x',
        hint:    'cos(35°) = x / 30',
        answer:  24.57,
        answerType: 'side',
        unit: '',
        triangle: {
          pts: { a:[25,110], b:[25,20], c:[155,110] },
          rightAt: 'a',
          sides:  [{ v1:'b', v2:'c', text:'30', dx: 14, dy:-9 },
                   { v1:'a', v2:'c', text:'x',  dx:  0, dy:16 }],
          angles: [{ v:'c', text:'35°', dx:-30, dy:-14 }],
        },
      },
      {
        id: 6,
        given:   ['Opposite side = 17', 'Angle = 12°'],
        find:    'the side adjacent to 12° — call it x',
        hint:    'tan(12°) = 17 / x',
        answer:  79.98,
        answerType: 'side',
        unit: '',
        triangle: {
          pts: { a:[25,20], b:[25,110], c:[155,110] },
          rightAt: 'b',
          sides:  [{ v1:'a', v2:'b', text:'x',  dx:-14, dy:0  },
                   { v1:'b', v2:'c', text:'17', dx:  0, dy:16 }],
          angles: [{ v:'a', text:'12°', dx:22, dy:16 }],
        },
      },
      {
        id: 7,
        given:   ['Leg = 4 (opposite to θ)', 'Hypotenuse = 8'],
        find:    'angle θ (in degrees)',
        hint:    'sin(θ) = 4 / 8',
        answer:  30,
        answerType: 'angle',
        unit: '°',
        triangle: {
          pts: { a:[25,20], b:[25,110], c:[155,20] },
          rightAt: 'a',
          sides:  [{ v1:'a', v2:'c', text:'4', dx:  0, dy:-14 },
                   { v1:'b', v2:'c', text:'8', dx: 14, dy:-9  }],
          angles: [{ v:'b', text:'θ', dx:22, dy:-14 }],
        },
      },
      {
        id: 8,
        given:   ['Adjacent side = 10', 'Hypotenuse = 10√2 ≈ 14.14'],
        find:    'angle θ (in degrees)',
        hint:    'cos(θ) = 10 / (10√2)',
        answer:  45,
        answerType: 'angle',
        unit: '°',
        triangle: {
          pts: { a:[155,20], b:[25,20], c:[155,110] },
          rightAt: 'a',
          sides:  [{ v1:'a', v2:'c', text:'10',   dx: 18, dy:0 },
                   { v1:'b', v2:'c', text:'10√2', dx:-18, dy:8 }],
          angles: [{ v:'c', text:'θ', dx:-26, dy:-14 }],
        },
      },
      {
        id: 9,
        given:   ['Leg = 6 (adjacent to θ)', 'Hypotenuse = 10'],
        find:    'angle θ (in degrees)',
        hint:    'cos(θ) = 6 / 10',
        answer:  53.13,
        answerType: 'angle',
        unit: '°',
        triangle: {
          pts: { a:[25,20], b:[25,110], c:[155,110] },
          rightAt: 'b',
          sides:  [{ v1:'a', v2:'b', text:'6',  dx:-14, dy:0  },
                   { v1:'a', v2:'c', text:'10', dx: 14, dy:-6 }],
          angles: [{ v:'a', text:'θ', dx:20, dy:16 }],
        },
      },
      {
        id: 10,
        given:   ['Leg = 14 (opposite to θ)', 'Leg = 48 (adjacent to θ)'],
        find:    'angle θ (in degrees)',
        hint:    'tan(θ) = 14 / 48',
        answer:  16.26,
        answerType: 'angle',
        unit: '°',
        triangle: {
          pts: { a:[25,110], b:[25,20], c:[155,110] },
          rightAt: 'a',
          sides:  [{ v1:'a', v2:'b', text:'14', dx:-16, dy:0  },
                   { v1:'a', v2:'c', text:'48', dx:  0, dy:16 }],
          angles: [{ v:'c', text:'θ', dx:-22, dy:-14 }],
        },
      },
    ],
  },
}
